### ISSUE TITLE
how about use BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by Freed-Wu** [wolfgitpr/cpp-pinyin#2]
https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

How about use official BUILD_SHARED_LIBS to replace CPP_PINYIN_STATIC?

**Comment by wolfgitpr** [comment]
Thank you for the suggestion, but I hope the project can be controlled separately as a submodule.

**Comment by Freed-Wu** [comment]
Oh, I means BUILD_SHARED_LIBS=ON means CPP_PINYIN_STATIC=OFF . not don't allow any sub module.
