### ISSUE TITLE
[feature] support pkg-config

### ISSUE THREAD

**Issue by Freed-Wu** [wolfgitpr/cpp-pinyin#3]
Add a cpp-pinyin.pc to support pkg-config

TIA!

**Comment by wolfgitpr** [comment]
The official vcpkg version will not be updated frequently, you can refer to the [example](https://github.com/flutydeer/ds-editor-lite/tree/main/scripts/vcpkg/ports/cpp-pinyin) deployment of a private port to try.

**Comment by Freed-Wu** [comment]
pkg-config is not cmake. it uses a `*.pc` to provide `CFLAGS`, `LDFLAGS` by `pkg-config --cflags`, `pkg-config --ldflags`.

**Comment by wolfgitpr** [comment]
> pkg-config is not cmake. it uses a `*.pc` to provide `CFLAGS`, `LDFLAGS` by `pkg-config --cflags`, `pkg-config --ldflags`.

The [dev branch](https://github.com/wolfgitpr/cpp-pinyin/tree/dev) root directory carries the [pc.in](https://github.com/wolfgitpr/cpp-pinyin/blob/dev/cpp-pinyin.pc.in) file, and after [installation](https://github.com/wolfgitpr/cpp-pinyin/blob/dev/CMakeLists.txt) line 167, the pc file appears.

![image](https://github.com/user-attachments/assets/7d0d2de9-4bb7-4f94-95e8-efdd63e9bf0e)

![image](https://github.com/user-attachments/assets/249cf067-f7ab-4a76-8981-e15e44c0361c)

**Comment by Freed-Wu** [comment]
Great. Hope dev can be merged early and a new version is released.
